### PR TITLE
Support upload to maven central.

### PR DESCRIPTION
**Pull request by mattak**
@chsh: Hi, I prepared upload settings for maven central. Could you merge it?

### CODE REVIEW

**Comment by karupanerura** [comment]
:+1:

**Comment by chsh** [comment]
@mattak Thanks! Are you interested in to become a collaborator of this repo? It's good for this library because it's few time to maintain this library for me. ;-)

**Comment by mattak** [comment]
@chsh Thanks for merge. I'm interested in to become a collaborator! :-)

**Comment by chsh** [comment]
:+1:

**Pull request merged**
